# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Garamgaebi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Garamgaebi
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'Then'
  
  target 'GaramgaebiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GaramgaebiUITests' do
    # Pods for testing
  end

end
