# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Garamgaebi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Garamgaebi
  pod 'SnapKit', '~> 5.6.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'Alamofire'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리 
  pod 'ReactorKit'
  pod 'Starscream'
  pod 'StompClientLib'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'  
  target 'GaramgaebiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GaramgaebiUITests' do
    # Pods for testing
  end

end
